export const REGISTER_SCREENS = 'REGISTER_SCREENS';
export const SEND_ERROR = 'SEND_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const ATTEMPT_SIGN_IN = 'ATTEMPT_SIGN_IN';
export const ATTEMPT_SIGN_OUT = 'ATTEMPT_SIGN_OUT';
export const ATTEMPT_CHECK_AUTH = 'ATTEMPT_CHECK_AUTH';
export const SET_ACTIVE_COMPONENT = 'SET_ACTIVE_COMPONENT';